### ISSUE TITLE
Совместимость с последними версиями MODX?

### ISSUE THREAD

**Issue by core01** [Fi1osof/modxRepository#7]
Совместим ли пакет с последними версиями MODX?
Будет ли он поддерживаться дальше? (хочется организовать свой репозиторий для личного пользования)

Собственно проблема:
Установил пакет на modx 2.4.2, создал все необходимые категории, пакеты, релизы.
На клиенте добавил источник и вся беда в том, что видны только категории, а пакеты нет.

**Comment by core01** [comment]
При установке не создалась TV downloads, ручное создание TV исправляет данную проблему.

**Comment by doitmaxim** [comment]
> 
> 
> Совместим ли пакет с последними версиями MODX?
> Будет ли он поддерживаться дальше? (хочется организовать свой репозиторий для личного пользования)
> 
> Собственно проблема:
> Установил пакет на modx 2.4.2, создал все необходимые категории, пакеты, релизы.
> На клиенте добавил источник и вся беда в том, что видны только категории, а пакеты нет.

Приветствую. К какому шаблону надо создать тв и какой тип ввода? Если, конечно, помнишь

**Comment by Fi1osof** [comment]
@doitmaxim вот здесь видео как устанавливать и настраивать https://www.youtube.com/watch?v=9EgYqTEX894
Но я не знаю насколько это актуально для последних версий MODX.

Проект этот переношу в архив, потому что MODX не занимаюсь уже давно.
